### ISSUE TITLE
Add sha1s to gmaven.bzl

### ISSUE THREAD

**Issue by mikelikespie** [bazelbuild/gmaven_rules#1]
This would improve security. Also I hypothesize that this will make things work better with `--experimental_repository_cache` flag. (not 100% sure how that works, but appears to work with other types of builds once a hash is added)

**Comment by jin** [comment]
These are Maven AARs, so they are cached in `~/.m2/` by default. They are not cached with `--experimental_repository_cache`.

**Comment by kamalmarhubi** [comment]
Adding sha256 would help with the repo cache, but sha1 wouldn't. I don't know how to do that short of downloading the whole repo and generating them.

**Comment by jin** [comment]
@kamalmarhubi as I've mentioned in the other issue, https://github.com/jin/rules_maven supports caching downloaded artifacts, although not by the repository cache mechanism.

**Comment by jin** [comment]
We've merged jin/rules_maven into this repo. The downloaded files can be cached if you turn on `maven_install.use_unsafe_shared_cache`.
