### ISSUE TITLE
Regenerate Rules

### ISSUE THREAD

**Issue by przemeklach** [bazelbuild/gmaven_rules#24]
Hi,

I regenerated gmaven.bzl because I needed a newer library. I'm hosting the file on my own server and I changed my URL as appropriate. 

When I try to run I get the following error:

ERROR: error loading package '': Encountered error while reading extension file 'gmaven.bzl': no such package '@gmaven_rules//': Prefix gmaven_rules-20180723 was given, but not found in the archive
ERROR: error loading package '': Encountered error while reading extension file 'gmaven.bzl': no such package '@gmaven_rules//': Prefix gmaven_rules-20180723 was given, but not found in the archive
INFO:

I've double checked what the original artifact looks like when using the artifact from https://github.com/bazelbuild/gmaven_rules/archive vs mine and it looks the same.

Any thoughts?

**Comment by jin** [comment]
What's the layout of your generated tarball? The `strip_prefix` option is because GitHub automatically packs it into a `gmaven_rules-$release` directory:

```
$ tar tf gmaven_rules-20180625-1.tar.gz
gmaven_rules-20180625-1/
gmaven_rules-20180625-1/.bazelci/
gmaven_rules-20180625-1/.bazelci/presubmit.yml
gmaven_rules-20180625-1/.gitignore
gmaven_rules-20180625-1/AUTHORS
gmaven_rules-20180625-1/BUILD
gmaven_rules-20180625-1/CONTRIBUTING.md
gmaven_rules-20180625-1/GMavenToBazel.java
gmaven_rules-20180625-1/LICENSE
gmaven_rules-20180625-1/README.md
gmaven_rules-20180625-1/WORKSPACE
gmaven_rules-20180625-1/defs.bzl
gmaven_rules-20180625-1/examples/
gmaven_rules-20180625-1/examples/AndroidManifest.xml
gmaven_rules-20180625-1/examples/BUILD
gmaven_rules-20180625-1/gmaven.bzl
gmaven_rules-20180625-1/import_external.bzl
```

**Comment by jin** [comment]
I just published a new release: https://github.com/bazelbuild/gmaven_rules/releases/tag/20180723-1

**Comment by shamtron** [comment]
Hi,

Your new release works. Thank you.

So I cloned your repo, built it, and then created a new tar using the following command:

tar -zcvf 20180723.tar.gz .

I then uploaded the artifact and modified my workspace file to:
GMAVEN_TAG = "20180723"

http_archive(
    name = "gmaven_rules",
    strip_prefix = "gmaven_rules-%s" % GMAVEN_TAG,
    url = "https://storage.googleapis.com/...../%s.tar.gz" % GMAVEN_TAG,
)

That didn't work. I then tried:

tar -zcvf gmaven_rules-20180723.tar.gz .

http_archive(
    name = "gmaven_rules",
    strip_prefix = "gmaven_rules-%s" % GMAVEN_TAG,
    url = "https://storage.googleapis.com/...../gmaven_rules-%s.tar.gz" % GMAVEN_TAG,
)

That didn't work either. The last error I got was:

ERROR: error loading package '': Encountered error while reading extension file 'gmaven.bzl': no such package '@gmaven_rules//': Prefix gmaven_rules-20180723 was given, but not found in the archive.

Perhaps its the way in which I'm taring?

**Comment by przemeklach** [comment]
Hi,

Your new release works. Thank you.

So I cloned your repo, built it, and then created a new tar using the following command:

tar -zcvf 20180723.tar.gz .

I then uploaded the artifact and modified my workspace file to:
GMAVEN_TAG = "20180723"

http_archive(
name = "gmaven_rules",
strip_prefix = "gmaven_rules-%s" % GMAVEN_TAG,
url = "https://storage.googleapis.com/...../%s.tar.gz" % GMAVEN_TAG,
)

That didn't work. I then tried:

tar -zcvf gmaven_rules-20180723.tar.gz .

http_archive(
name = "gmaven_rules",
strip_prefix = "gmaven_rules-%s" % GMAVEN_TAG,
url = "https://storage.googleapis.com/...../gmaven_rules-%s.tar.gz" % GMAVEN_TAG,
)

That didn't work either. The last error I got was:

ERROR: error loading package '': Encountered error while reading extension file 'gmaven.bzl': no such package '@gmaven_rules//': Prefix gmaven_rules-20180723 was given, but not found in the archive.

Perhaps its the way in which I'm taring?

**Comment by jin** [comment]
could you do a `tar tf` on your tarfile? you may not need the `strip_prefix` attribute if the contents are not packed into a subdirectory.

**Comment by przemeklach** [comment]
tar tf ~/Downloads/gmaven_rules-20180723.tar.gz
./
./._.DS_Store
./.DS_Store
./._gmaven.bzl
./gmaven.bzl
./.bazelci/
./LICENSE
./BUILD
./AUTHORS
./CONTRIBUTING.md
./WORKSPACE
./.gitignore
./README.md
./examples/
./GMavenToBazel.java
./GMavenToBazel$Artifact.class
./import_external.bzl
./defs.bzl
./GMavenToBazel.class
./examples/BUILD
./examples/AndroidManifest.xml
./.bazelci/presubmit.yml

**Comment by przemeklach** [comment]
Ya I just verified it. In my case on prefix stripping is required. 

Thank you for your help.

**Comment by jin** [comment]
@przemeklach great!
