### ISSUE TITLE
Optionally add artifacts from jcenter or mavencentral for missing dependencies

### ISSUE THREAD

**Issue by kamalmarhubi** [bazelbuild/gmaven_rules#29]
I just switched a project over to this, but there are some artifacts that don't have all their dependencies if imported this way as they're not present in google's maven repo.

Would you accept a patch to optionally include those dependencies by bringing them in from one of the public maven repos?

**Comment by jin** [comment]
Hey, I'm working on a replacement repository rule for gmaven_rules that supports this (and much more). Check it out here: https://github.com/jin/rules_maven

gmaven_rules is also limited in other ways, and I'd prefer to switch to an approach that solves all of them at once.
